namespace: anita
appName: anita-nextjs-app
hostname: anita.appstellar.training
app: nextjs
service: nextjs-service
ingress: nextjs-ingress
ingressAnnotations:
  kubernetes.io/ingress.class: alb
  alb.ingress.kubernetes.io/scheme: internet-facing
  alb.ingress.kubernetes.io/target-type: ip
  alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:313422618945:certificate/a9dce0fe-3d8c-42ea-897b-4c5422817d0f
  alb.ingress.kubernetes.io/tags: Name=appstellar-training-tali, Environment=dev
  alb.ingress.kubernetes.io/group.name: appstellar-training-tali
  alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  alb.ingress.kubernetes.io/ssl-redirect: '443'
replicas: 1
imagePullPolicy: IfNotPresent
imageName: 313422618945.dkr.ecr.eu-central-1.amazonaws.com/anita-nextjs-app
imageTag: 06e2f2b61294a29ed0aaec67ec06571158cea5dc
servicePort : 80
containerPort: 3000
livenessProbe: 
 initialDelaySeconds: 15
 periodSeconds: 20



